### ISSUE TITLE
Implementing a Reusable Feedback Delay • related documentation 

### ISSUE THREAD

**Issue by s-stc** [ircam-ismm/webaudio-tutorials#9]
Les liens ne sont plus à jour (mais mdn propose quand même des redirections)

**Comment by s-stc** [comment]
idem dans Timing and Scheduling : [AudioContext.currentTime](https://developer.mozilla.org/docs/Web/API/BaseAudioContext/currentTime) n'existe plus

**Comment by b-ma** [comment]
fixed in #bce429c
